import './header';
import './effects-list';
import './details-id';
import './details-type';
import './details-equip';
import './details-activation';
import './details-damage';
import './properties';
import './talent-prerequisites';
